spring:
  application:
    name: swagger
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:D:\develop\h2\data\swagger
    username: admin
    password: 123456

server:
  port: 8888
